### ISSUE TITLE
Web-Application - Researchers interface - Meeting with Analytics action items

### ISSUE THREAD

**Issue by MeiravDaniel** [Prize4Life/als#39]
1.      To each Get API will add the patient data (exclude email and name) , because patient API will be blocked.
2.      Drawing
 
        Need the image and the draw the users did  separately 
        Names and IDs accurate and specific to each drawing 
3.      Steps –
        Reduce the '5' sec .(@Ari)
4.      Speech tests –
a.      Add timing client (@Ari)
b.      Add timing server
5.      @Dev – sync with Ari regarding the data
6.      @Dev with Ari - Verify that the cannot be affected by miss use of app (leaving it open or  so)

**Comment by ari** [comment]
I have nothing to do with this project, so please send your notifications somewhere else.
